name: SmORFinder Tests (Docker)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        # Build the Docker image
        docker build -t smorfinder-test .
        echo "Docker image built successfully"
    
    - name: List test files
      run: |
        echo "Available test genome files:"
        ls -la test/genome_files/
        echo "Checking for required files..."
        for genome in test/genome_files/*.fna; do
          if [ -f "$genome" ]; then
            genome_name=$(basename "$genome" .fna)
            echo "Found genome: $genome_name"
            if [ -f "test/genome_files/${genome_name}.faa" ] && [ -f "test/genome_files/${genome_name}.gff" ]; then
              echo "✓ All files present for $genome_name"
            else
              echo "✗ Missing .faa or .gff for $genome_name"
            fi
          fi
        done
    
    - name: Run standard SmORFinder in Docker
      run: |
        # Run standard SmORFinder using Docker
        docker run --rm -v $(pwd)/test/genome_files:/data -v $(pwd)/test_output_standard:/output smorfinder-test \
          bash -c "cd /data && smorf single genome1.fna --outdir /output --force"
    
    - name: Run custom SmORFinder in Docker
      run: |
        # Run custom SmORFinder using Docker
        docker run --rm -v $(pwd)/test/genome_files:/data -v $(pwd)/test_output_custom:/output smorfinder-test \
          bash -c "cd /data && smorf custom genome1.fna genome1.faa genome1.gff --outdir /output --force"
    
    - name: Create comparison script
      run: |
        mkdir -p scripts
        cat > scripts/compare_results.py << 'EOF'
        #!/usr/bin/env python3
        """
        Compare results from standard and custom SmORFinder runs.
        Ensures identical protein sequences except for headers.
        """
        
        import sys
        import os
        from Bio import SeqIO
        
        def normalize_fasta_headers(fasta_file):
            """Extract protein sequences and sort them for comparison."""
            sequences = []
            for record in SeqIO.parse(fasta_file, 'fasta'):
                sequences.append(str(record.seq))
            return sorted(sequences)
        
        def compare_fasta_files(file1, file2, description):
            """Compare two FASTA files by their sequences (ignoring headers)."""
            print(f"\nComparing {description}...")
            
            if not os.path.exists(file1):
                print(f"ERROR: {file1} not found")
                return False
            if not os.path.exists(file2):
                print(f"ERROR: {file2} not found")
                return False
            
            seqs1 = normalize_fasta_headers(file1)
            seqs2 = normalize_fasta_headers(file2)
            
            if seqs1 == seqs2:
                print(f"✓ {description}: Sequences are identical ({len(seqs1)} proteins)")
                return True
            else:
                print(f"✗ {description}: Sequences differ!")
                print(f"  Standard: {len(seqs1)} proteins")
                print(f"  Custom: {len(seqs2)} proteins")
                return False
        
        def main():
            print("SmORFinder Results Comparison (Docker)")
            print("=" * 40)
            
            # Test genome1
            standard_faa = "test_output_standard/test_output_standard.faa"
            custom_faa = "test_output_custom/test_output_custom.faa"
            
            if compare_fasta_files(standard_faa, custom_faa, "genome1 protein sequences"):
                print("\n" + "=" * 40)
                print("✓ ALL TESTS PASSED: Results are identical except for headers")
                sys.exit(0)
            else:
                print("\n" + "=" * 40)
                print("✗ TESTS FAILED: Results differ between standard and custom runs")
                sys.exit(1)
        
        if __name__ == '__main__':
            main()
        EOF
        chmod +x scripts/compare_results.py
    
    - name: Compare results
      run: |
        python scripts/compare_results.py
    
    - name: Show test output structure
      run: |
        echo "=== Test Output Structure ==="
        find test_output_* -name "*.faa" -o -name "*.tsv" | head -10
        echo "=== File sizes ==="
        du -h test_output_*
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-docker
        path: |
          test_output_*/
          test/genome_files/
          scripts/ 